// This file is part of https://github.com/KurtBoehm/grex.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef INCLUDE_GREX_BACKEND_X86_MACROS_INTRINSICS_HPP
#define INCLUDE_GREX_BACKEND_X86_MACROS_INTRINSICS_HPP

#include "grex/backend/x86/macros/base.hpp"
#include "grex/backend/x86/macros/math.hpp"

// Components used in various intrinsics (maths-related components are in math.hpp)

#define GREX_FP_LETTER_32 s
#define GREX_FP_LETTER_64 d
#define GREX_FP_LETTER(BITS) GREX_FP_LETTER_##BITS
#define GREX_FP_SUFFIX(BITS) GREX_CAT(p, GREX_FP_LETTER(BITS))

#define GREX_SI_SUFFIX_f(BITS, REGISTERBITS, FP) FP
#define GREX_SI_SUFFIX_i(BITS, REGISTERBITS, FP) si##REGISTERBITS
#define GREX_SI_SUFFIX_u(BITS, REGISTERBITS, FP) si##REGISTERBITS
#define GREX_SI_SUFFIX(KIND, BITS, REGISTERBITS) \
  GREX_SI_SUFFIX_##KIND(BITS, REGISTERBITS, GREX_FP_SUFFIX(BITS))
#define GREX_SIR_SUFFIX(KIND, BITS, REGISTERBITS) \
  GREX_SI_SUFFIX_##KIND(BITS, REGISTERBITS, GREX_CAT(GREX_FP_SUFFIX(BITS), REGISTERBITS))

#define GREX_REGISTER_SUFFIX_f32
#define GREX_REGISTER_SUFFIX_f64 d
#define GREX_REGISTER_SUFFIX_f(BITS) GREX_REGISTER_SUFFIX_f##BITS
#define GREX_REGISTER_SUFFIX_i(BITS) i
#define GREX_REGISTER_SUFFIX_u(BITS) i
#define GREX_REGISTER_SUFFIX(KIND, BITS) GREX_REGISTER_SUFFIX_##KIND(BITS)

#define GREX_EP_SUFFIX_f(BITS, FALLBACK) GREX_FP_SUFFIX(BITS)
#define GREX_EP_SUFFIX_i(BITS, FALLBACK) FALLBACK
#define GREX_EP_SUFFIX_u(BITS, FALLBACK) FALLBACK
#define GREX_EP_SUFFIX(KIND, BITS, FALLBACK) GREX_EP_SUFFIX_##KIND(BITS, FALLBACK)
#define GREX_EPI_SUFFIX(KIND, BITS) GREX_EP_SUFFIX(KIND, BITS, epi##BITS)
#define GREX_EPU_SUFFIX(KIND, BITS) GREX_EP_SUFFIX(KIND, BITS, ep##KIND##BITS)
#define GREX_EPI8_SUFFIX(KIND, BITS) GREX_EP_SUFFIX(KIND, BITS, epi8)

#define GREX_BITPREFIX_128 _mm
#define GREX_BITPREFIX_256 _mm256
#define GREX_BITPREFIX_512 _mm512
#define GREX_BITPREFIX(REGISTERBITS) GREX_BITPREFIX_##REGISTERBITS

#define GREX_BITNS_128 mm
#define GREX_BITNS_256 mm256
#define GREX_BITNS_512 mm512
#define GREX_BITNS(REGISTERBITS) GREX_BITNS_##REGISTERBITS

#define GREX_KINDCAST_IMPL(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS) \
  GREX_CAT(GREX_BITPREFIX(REGISTERBITS), _cast, GREX_SI_SUFFIX(SRCKIND, SRCBITS, REGISTERBITS), _, \
           GREX_SI_SUFFIX(DSTKIND, DSTBITS, REGISTERBITS)) \
  (X)

#define GREX_KINDCAST_f32f32(X, ...) X
#define GREX_KINDCAST_f32f64 GREX_KINDCAST_IMPL
#define GREX_KINDCAST_f64f32 GREX_KINDCAST_IMPL
#define GREX_KINDCAST_f64f64(X, ...) X
#define GREX_KINDCAST_ff(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS) \
  GREX_KINDCAST_f##SRCBITS##f##DSTBITS(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS)
#define GREX_KINDCAST_fi GREX_KINDCAST_IMPL
#define GREX_KINDCAST_fu GREX_KINDCAST_IMPL
#define GREX_KINDCAST_if GREX_KINDCAST_IMPL
#define GREX_KINDCAST_ii(X, ...) X
#define GREX_KINDCAST_iu(X, ...) X
#define GREX_KINDCAST_uf GREX_KINDCAST_IMPL
#define GREX_KINDCAST_ui(X, ...) X
#define GREX_KINDCAST_uu(X, ...) X
#define GREX_KINDCAST(SRCKIND, DSTKIND, BITS, REGISTERBITS, X) \
  GREX_KINDCAST_##SRCKIND##DSTKIND(X, SRCKIND, BITS, DSTKIND, BITS, REGISTERBITS)
#define GREX_KINDCAST_EXT(DSTKIND, DSTBITS, SRCKIND, SRCBITS, REGISTERBITS, X) \
  GREX_KINDCAST_##SRCKIND##DSTKIND(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS)

#define GREX_KINDCAST_SI_i8i8(X, ...) X
#define GREX_KINDCAST_SI_i8i16(X, ...) i8(X)
#define GREX_KINDCAST_SI_i8i32(X, ...) i8(X)
#define GREX_KINDCAST_SI_i8i64(X, ...) i8(X)
#define GREX_KINDCAST_SI_i16i8(X, ...) i16(X)
#define GREX_KINDCAST_SI_i16i16(X, ...) X
#define GREX_KINDCAST_SI_i16i32(X, ...) i16(X)
#define GREX_KINDCAST_SI_i16i64(X, ...) i16(X)
#define GREX_KINDCAST_SI_i32i8(X, ...) i32(X)
#define GREX_KINDCAST_SI_i32i16(X, ...) i32(X)
#define GREX_KINDCAST_SI_i32i32(X, ...) X
#define GREX_KINDCAST_SI_i32i64(X, ...) i32(X)
#define GREX_KINDCAST_SI_i64i8(X, ...) i64(X)
#define GREX_KINDCAST_SI_i64i16(X, ...) i64(X)
#define GREX_KINDCAST_SI_i64i32(X, ...) i64(X)
#define GREX_KINDCAST_SI_i64i64(X, ...) X

#define GREX_KINDCAST_SI_ff(X, ...) X
#define GREX_KINDCAST_SI_fi(X, DSTBITS, SRCBITS) f##DSTBITS(X)
#define GREX_KINDCAST_SI_fu(X, DSTBITS, SRCBITS) f##DSTBITS(X)
#define GREX_KINDCAST_SI_if(X, DSTBITS, SRCBITS) i##DSTBITS(X)
#define GREX_KINDCAST_SI_ii(X, DSTBITS, SRCBITS) \
  GREX_KINDCAST_SI_i##DSTBITS##i##SRCBITS(X, DSTBITS, SRCBITS)
#define GREX_KINDCAST_SI_iu(X, DSTBITS, SRCBITS) i##DSTBITS(X)
#define GREX_KINDCAST_SI_uf(X, DSTBITS, SRCBITS) u##DSTBITS(X)
#define GREX_KINDCAST_SI_ui(X, DSTBITS, SRCBITS) u##DSTBITS(X)
#define GREX_KINDCAST_SI_uu(X, ...) X
#define GREX_KINDCAST_SINGLE(SRCKIND, DSTKIND, BITS, X) \
  GREX_KINDCAST_SI_##DSTKIND##SRCKIND(X, BITS, BITS)
#define GREX_KINDCAST_SINGLE_EXT(DSTKIND, DSTBITS, SRCKIND, SRCBITS, X) \
  GREX_KINDCAST_SI_##DSTKIND##SRCKIND(X, DSTBITS, SRCBITS)

#define GREX_OPCAST_i8(KIND, BITS, X) KIND##BITS(X)
#define GREX_OPCAST_i16(KIND, BITS, X) KIND##BITS(X)
#define GREX_OPCAST_i32(KIND, BITS, X) X
#define GREX_OPCAST_i64(KIND, BITS, X) X
#define GREX_OPCAST_f32(KIND, BITS, X) X
#define GREX_OPCAST_f64(KIND, BITS, X) X
#define GREX_OPCAST_f(KIND, BITS, X) GREX_OPCAST_f##BITS(KIND, BITS, X)
#define GREX_OPCAST_i(KIND, BITS, X) GREX_OPCAST_i##BITS(KIND, BITS, X)
#define GREX_OPCAST_u(KIND, BITS, X) GREX_OPCAST_i##BITS(KIND, BITS, X)
#define GREX_OPCAST(KIND, BITS, X) GREX_OPCAST_##KIND(KIND, BITS, X)

#define GREX_MMASK(SIZE) GREX_CAT(__mmask, GREX_MAX(SIZE, 8))
#define GREX_MMASK_CAST_16(SIZE, X) GREX_MMASK(SIZE)(X)
#define GREX_MMASK_CAST_32(SIZE, X) X
#define GREX_MMASK_CAST_64(SIZE, X) X
#define GREX_MMASK_CAST(SIZE, X) GREX_CAT(GREX_MMASK_CAST_, GREX_MAX(SIZE, 16))(SIZE, X)

// Map a kind to its signed counterpart
#define GREX_SIGNED_KIND_f f
#define GREX_SIGNED_KIND_i i
#define GREX_SIGNED_KIND_u i
#define GREX_SIGNED_KIND(KIND) GREX_SIGNED_KIND_##KIND

// Casts to the argument type of the argument of various set-like intrinsics
#define GREX_SIGNED_CAST_f(BITS, X) X
#define GREX_SIGNED_CAST_i(BITS, X) X
#define GREX_SIGNED_CAST_u(BITS, X) i##BITS(X)
#define GREX_SIGNED_CAST(KIND, BITS, X) GREX_SIGNED_CAST_##KIND(BITS, X)

#endif // INCLUDE_GREX_BACKEND_X86_MACROS_INTRINSICS_HPP
