// This file is part of https://github.com/KurtBoehm/grex.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef INCLUDE_GREX_BACKEND_X86_MACROS_INTRINSICS_HPP
#define INCLUDE_GREX_BACKEND_X86_MACROS_INTRINSICS_HPP

#include "grex/backend/x86/macros/base.hpp"
#include "grex/backend/x86/macros/math.hpp"

// Components used in various intrinsics (maths-related components are in math.hpp)

#define GREX_FP_LETTER_32 s
#define GREX_FP_LETTER_64 d
#define GREX_FP_LETTER(BITS) GREX_FP_LETTER_##BITS
#define GREX_FP_SUFFIX(BITS) GREX_CAT(p, GREX_FP_LETTER(BITS))

#define GREX_SI_SUFFIX_f(BITS, REGISTERBITS, FP) FP
#define GREX_SI_SUFFIX_i(BITS, REGISTERBITS, FP) si##REGISTERBITS
#define GREX_SI_SUFFIX_u(BITS, REGISTERBITS, FP) si##REGISTERBITS
#define GREX_SI_SUFFIX(KIND, BITS, REGISTERBITS) \
  GREX_SI_SUFFIX_##KIND(BITS, REGISTERBITS, GREX_FP_SUFFIX(BITS))
#define GREX_SIR_SUFFIX(KIND, BITS, REGISTERBITS) \
  GREX_SI_SUFFIX_##KIND(BITS, REGISTERBITS, GREX_CAT(GREX_FP_SUFFIX(BITS), REGISTERBITS))

#define GREX_REGISTER_SUFFIX_f32
#define GREX_REGISTER_SUFFIX_f64 d
#define GREX_REGISTER_SUFFIX_f(BITS) GREX_REGISTER_SUFFIX_f##BITS
#define GREX_REGISTER_SUFFIX_i(BITS) i
#define GREX_REGISTER_SUFFIX_u(BITS) i
#define GREX_REGISTER_SUFFIX(KIND, BITS) GREX_REGISTER_SUFFIX_##KIND(BITS)

#define GREX_EP_SUFFIX_f(BITS, FALLBACK) GREX_FP_SUFFIX(BITS)
#define GREX_EP_SUFFIX_i(BITS, FALLBACK) FALLBACK
#define GREX_EP_SUFFIX_u(BITS, FALLBACK) FALLBACK
#define GREX_EP_SUFFIX(KIND, BITS, FALLBACK) GREX_EP_SUFFIX_##KIND(BITS, FALLBACK)
#define GREX_EPI_SUFFIX(KIND, BITS) GREX_EP_SUFFIX(KIND, BITS, epi##BITS)
#define GREX_EPU_SUFFIX(KIND, BITS) GREX_EP_SUFFIX(KIND, BITS, ep##KIND##BITS)
#define GREX_EPI8_SUFFIX(KIND, BITS) GREX_EP_SUFFIX(KIND, BITS, epi8)

#define GREX_BITPREFIX_128 _mm
#define GREX_BITPREFIX_256 _mm256
#define GREX_BITPREFIX_512 _mm512
#define GREX_BITPREFIX(REGISTERBITS) GREX_BITPREFIX_##REGISTERBITS

#define GREX_KINDCAST_IMPL(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS) \
  GREX_CAT(GREX_BITPREFIX(REGISTERBITS), _cast, GREX_SI_SUFFIX(SRCKIND, SRCBITS, REGISTERBITS), _, \
           GREX_SI_SUFFIX(DSTKIND, DSTBITS, REGISTERBITS)) \
  (X)

#define GREX_KINDCAST_f32f32(X, ...) X
#define GREX_KINDCAST_f32f64 GREX_KINDCAST_IMPL
#define GREX_KINDCAST_f64f32 GREX_KINDCAST_IMPL
#define GREX_KINDCAST_f64f64(X, ...) X
#define GREX_KINDCAST_ff(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS) \
  GREX_KINDCAST_f##SRCBITS##f##DSTBITS(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS)
#define GREX_KINDCAST_fi GREX_KINDCAST_IMPL
#define GREX_KINDCAST_fu GREX_KINDCAST_IMPL
#define GREX_KINDCAST_if GREX_KINDCAST_IMPL
#define GREX_KINDCAST_ii(X, ...) X
#define GREX_KINDCAST_iu(X, ...) X
#define GREX_KINDCAST_uf GREX_KINDCAST_IMPL
#define GREX_KINDCAST_ui(X, ...) X
#define GREX_KINDCAST_uu(X, ...) X
#define GREX_KINDCAST(SRCKIND, DSTKIND, BITS, REGISTERBITS, X) \
  GREX_KINDCAST_##SRCKIND##DSTKIND(X, SRCKIND, BITS, DSTKIND, BITS, REGISTERBITS)
#define GREX_KINDCAST_EXT(DSTKIND, DSTBITS, SRCKIND, SRCBITS, REGISTERBITS, X) \
  GREX_KINDCAST_##SRCKIND##DSTKIND(X, SRCKIND, SRCBITS, DSTKIND, DSTBITS, REGISTERBITS)

#define GREX_KINDCAST_SI_ff(X, ...) X
#define GREX_KINDCAST_SI_fi(X, BITS) i##BITS(X)
#define GREX_KINDCAST_SI_fu(X, BITS) u##BITS(X)
#define GREX_KINDCAST_SI_if(X, BITS) f##BITS(X)
#define GREX_KINDCAST_SI_ii(X, ...) X
#define GREX_KINDCAST_SI_iu(X, BITS) u##BITS(X)
#define GREX_KINDCAST_SI_uf(X, BITS) f##BITS(X)
#define GREX_KINDCAST_SI_ui(X, BITS) i##BITS(X)
#define GREX_KINDCAST_SI_uu(X, ...) X
#define GREX_KINDCAST_SINGLE(SRCKIND, DSTKIND, BITS, X) GREX_KINDCAST_SI_##SRCKIND##DSTKIND(X, BITS)

#define GREX_MMASK(SIZE) GREX_CAT(__mmask, GREX_MAX(SIZE, 8))

// Map a kind to its signed counterpart
#define GREX_SIGNED_KIND_f f
#define GREX_SIGNED_KIND_i i
#define GREX_SIGNED_KIND_u i
#define GREX_SIGNED_KIND(KIND) GREX_SIGNED_KIND_##KIND

// Casts to the argument type of the argument of various set-like intrinsics
#define GREX_SIGNED_CAST_f(BITS, X) X
#define GREX_SIGNED_CAST_i(BITS, X) X
#define GREX_SIGNED_CAST_u(BITS, X) i##BITS(X)
#define GREX_SIGNED_CAST(KIND, BITS, X) GREX_SIGNED_CAST_##KIND(BITS, X)

#endif // INCLUDE_GREX_BACKEND_X86_MACROS_INTRINSICS_HPP
