// This file is part of https://github.com/KurtBoehm/grex.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef INCLUDE_GREX_BACKEND_X86_MACROS_MULTIVERSION_HPP
#define INCLUDE_GREX_BACKEND_X86_MACROS_MULTIVERSION_HPP

#include "grex/backend/macros/transform.hpp"
#include "grex/backend/x86/cpuid.hpp" // IWYU pragma: keep

#define GREX_MULTIVERS_PARAM_I(X) X
#define GREX_MULTIVERS_PARAM(PARAM) GREX_MULTIVERS_PARAM_I PARAM
#define GREX_MULTIVERS_PARAMS(...) (GREX_TRANSFORM(GREX_MULTIVERS_PARAM __VA_OPT__(, ) __VA_ARGS__))

#define GREX_MULTIVERS_ARG_I(X)
#define GREX_MULTIVERS_ARG(PARAM) GREX_MULTIVERS_ARG_I PARAM
#define GREX_MULTIVERS_ARGS(...) (GREX_TRANSFORM(GREX_MULTIVERS_ARG __VA_OPT__(, ) __VA_ARGS__))

#define GREX_MULTIVERS_NS_I(LEVEL) x86_64_v##LEVEL
#define GREX_MULTIVERS_NS(LEVEL) GREX_MULTIVERS_NS_I(LEVEL)

#define GREX_MULTIVERS_DECLARE(LEVEL, RETURN, NAME, PARAMS) \
  namespace GREX_MULTIVERS_NS(LEVEL) { \
  RETURN NAME GREX_MULTIVERS_PARAMS PARAMS; \
  }

#define GREX_MULTIVERS_DECLARE_ALL_I(RETURN, NAME, PARAMS) \
  GREX_MULTIVERS_DECLARE(1, RETURN, NAME, PARAMS) \
  GREX_MULTIVERS_DECLARE(2, RETURN, NAME, PARAMS) \
  GREX_MULTIVERS_DECLARE(3, RETURN, NAME, PARAMS) \
  GREX_MULTIVERS_DECLARE(4, RETURN, NAME, PARAMS)
#define GREX_MULTIVERS_DECLARE_ALL(...) GREX_MULTIVERS_DECLARE_ALL_I(__VA_ARGS__)

#define GREX_MULTIVERS_DEFINE_I(LEVEL, RETURN, NAME, PARAMS) \
  GREX_MULTIVERS_DECLARE(LEVEL, RETURN, NAME, PARAMS) \
  RETURN GREX_MULTIVERS_NS(LEVEL)::NAME GREX_MULTIVERS_PARAMS PARAMS
#define GREX_MULTIVERS_DEFINE(...) GREX_MULTIVERS_DEFINE_I(__VA_ARGS__)

#define GREX_MULTIVERS_RESOLVER_I(RETURN, NAME, PARAMS) \
  RETURN NAME GREX_MULTIVERS_PARAMS PARAMS { \
    const unsigned int level = ::grex::backend::runtime_x86_64_level(); \
    if (level >= 4) { \
      return GREX_MULTIVERS_NS(4)::NAME GREX_MULTIVERS_ARGS PARAMS; \
    } \
    if (level == 3) { \
      return GREX_MULTIVERS_NS(3)::NAME GREX_MULTIVERS_ARGS PARAMS; \
    } \
    if (level == 2) { \
      return GREX_MULTIVERS_NS(2)::NAME GREX_MULTIVERS_ARGS PARAMS; \
    } \
    return GREX_MULTIVERS_NS(1)::NAME GREX_MULTIVERS_ARGS PARAMS; \
  }
#define GREX_MULTIVERS_RESOLVER(...) GREX_MULTIVERS_RESOLVER_I(__VA_ARGS__)

#endif // INCLUDE_GREX_BACKEND_X86_MACROS_MULTIVERSION_HPP
