// This file is part of https://github.com/KurtBoehm/grex.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef INCLUDE_GREX_BACKEND_X86_MACROS_TRANSFORM_HPP
#define INCLUDE_GREX_BACKEND_X86_MACROS_TRANSFORM_HPP

#include "grex/backend/x86/macros/base.hpp"

// Transform each argument
#define GREX_TRANSFORM_0(TRANS)
#define GREX_TRANSFORM_1(TRANS, X0) TRANS(X0)
#define GREX_TRANSFORM_2(TRANS, X0, X1) TRANS(X0), TRANS(X1)
#define GREX_TRANSFORM_3(TRANS, X0, X1, X2) TRANS(X0), TRANS(X1), TRANS(X2)
#define GREX_TRANSFORM_4(TRANS, X0, X1, X2, X3) TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3)
#define GREX_TRANSFORM_5(TRANS, X0, X1, X2, X3, X4) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4)
#define GREX_TRANSFORM_6(TRANS, X0, X1, X2, X3, X4, X5) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5)
#define GREX_TRANSFORM_7(TRANS, X0, X1, X2, X3, X4, X5, X6) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6)
#define GREX_TRANSFORM_8(TRANS, X0, X1, X2, X3, X4, X5, X6, X7) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7)
#define GREX_TRANSFORM_9(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), TRANS(X8)
#define GREX_TRANSFORM_10(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9)
#define GREX_TRANSFORM_11(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9), TRANS(X10)
#define GREX_TRANSFORM_12(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9), TRANS(X10), TRANS(X11)
#define GREX_TRANSFORM_13(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9), TRANS(X10), TRANS(X11), TRANS(X12)
#define GREX_TRANSFORM_14(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9), TRANS(X10), TRANS(X11), TRANS(X12), TRANS(X13)
#define GREX_TRANSFORM_15(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9), TRANS(X10), TRANS(X11), TRANS(X12), TRANS(X13), TRANS(X14)
#define GREX_TRANSFORM_16(TRANS, X0, X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, \
                          X15) \
  TRANS(X0), TRANS(X1), TRANS(X2), TRANS(X3), TRANS(X4), TRANS(X5), TRANS(X6), TRANS(X7), \
    TRANS(X8), TRANS(X9), TRANS(X10), TRANS(X11), TRANS(X12), TRANS(X13), TRANS(X14), TRANS(X15)
#define GREX_TRANSFORM_II(SIZE, TRANS, ...) GREX_TRANSFORM_##SIZE(TRANS __VA_OPT__(, ) __VA_ARGS__)
#define GREX_TRANSFORM_I(SIZE, TRANS, ...) GREX_TRANSFORM_II(SIZE, TRANS __VA_OPT__(, ) __VA_ARGS__)
#define GREX_TRANSFORM(TRANS, ...) \
  GREX_TRANSFORM_I(GREX_VARIADIC_SIZE(__VA_ARGS__), TRANS __VA_OPT__(, ) __VA_ARGS__)

#endif // INCLUDE_GREX_BACKEND_X86_MACROS_TRANSFORM_HPP
