// This file is part of https://github.com/KurtBoehm/grex.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef INCLUDE_GREX_BACKEND_X86_OPERATIONS_HELPERS_HPP
#define INCLUDE_GREX_BACKEND_X86_OPERATIONS_HELPERS_HPP

#include "grex/backend/x86/instruction-sets.hpp"

#define GREX_IDENTITY(X) X
#define GREX_APPLY(MACRO, ...) MACRO(__VA_ARGS__)

#define GREX_FP_SUFFIX_f32 ps
#define GREX_FP_SUFFIX_f64 pd
#define GREX_FP_SUFFIX(TYPE) GREX_FP_SUFFIX_##TYPE

#define GREX_ELEMENTS_128_8 16
#define GREX_ELEMENTS_128_16 8
#define GREX_ELEMENTS_128_32 4
#define GREX_ELEMENTS_128_64 2
#define GREX_ELEMENTS_256_8 32
#define GREX_ELEMENTS_256_16 16
#define GREX_ELEMENTS_256_32 8
#define GREX_ELEMENTS_256_64 4
#define GREX_ELEMENTS_512_8 64
#define GREX_ELEMENTS_512_16 32
#define GREX_ELEMENTS_512_32 16
#define GREX_ELEMENTS_512_64 8
#define GREX_ELEMENTS(REGISTERBITS, ELEMENTBITS) GREX_ELEMENTS_##REGISTERBITS##_##ELEMENTBITS

#define GREX_REGISTERBITS_PREFIX_128 mm
#define GREX_REGISTERBITS_PREFIX_256 mm256
#define GREX_REGISTERBITS_PREFIX_512 mm512
#define GREX_REGISTERBITS_PREFIX(REGISTERBITS) GREX_REGISTERBITS_PREFIX_##REGISTERBITS

#define GREX_DEFINE_SI_OPERATION(MACRO, REGISTERBITS, ...) \
  MACRO(u8, GREX_ELEMENTS(REGISTERBITS, 8) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i8, GREX_ELEMENTS(REGISTERBITS, 8) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(u16, GREX_ELEMENTS(REGISTERBITS, 16) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i16, GREX_ELEMENTS(REGISTERBITS, 16) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(u32, GREX_ELEMENTS(REGISTERBITS, 32) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i32, GREX_ELEMENTS(REGISTERBITS, 32) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(u64, GREX_ELEMENTS(REGISTERBITS, 64) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i64, GREX_ELEMENTS(REGISTERBITS, 64) __VA_OPT__(, ) __VA_ARGS__)

#define GREX_DEFINE_SI_OPERATION_EXT(MACRO, REGISTERBITS, ...) \
  MACRO(u, 8, GREX_ELEMENTS(REGISTERBITS, 8) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i, 8, GREX_ELEMENTS(REGISTERBITS, 8) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(u, 16, GREX_ELEMENTS(REGISTERBITS, 16) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i, 16, GREX_ELEMENTS(REGISTERBITS, 16) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(u, 32, GREX_ELEMENTS(REGISTERBITS, 32) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i, 32, GREX_ELEMENTS(REGISTERBITS, 32) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(u, 64, GREX_ELEMENTS(REGISTERBITS, 64) __VA_OPT__(, ) __VA_ARGS__) \
  MACRO(i, 64, GREX_ELEMENTS(REGISTERBITS, 64) __VA_OPT__(, ) __VA_ARGS__)

#if GREX_INSTRUCTION_SET >= GREX_AVX512_2
#define GREX_DEFINE_INSTR_SET(FPMACRO, INTMACRO) \
  FPMACRO(128, mm) \
  INTMACRO(128, mm) \
  FPMACRO(256, mm256) \
  INTMACRO(256, mm256) \
  FPMACRO(512, mm512) \
  INTMACRO(512, mm512)
#elif GREX_INSTRUCTION_SET >= GREX_AVX512_1
#define GREX_DEFINE_INSTR_SET(FPMACRO, INTMACRO) \
  FPMACRO(128, mm) \
  INTMACRO(128, mm) \
  FPMACRO(256, mm256) \
  INTMACRO(256, mm256) \
  FPMACRO(512, mm512)
#elif GREX_INSTRUCTION_SET >= GREX_AVX2
#define GREX_DEFINE_INSTR_SET(FPMACRO, INTMACRO) \
  FPMACRO(128, mm) \
  INTMACRO(128, mm) \
  FPMACRO(256, mm256) \
  INTMACRO(256, mm256)
#elif GREX_INSTRUCTION_SET >= GREX_AVX
#define GREX_DEFINE_INSTR_SET(FPMACRO, INTMACRO) \
  FPMACRO(128, mm) \
  INTMACRO(128, mm) \
  FPMACRO(256, mm256)
#else
#define GREX_DEFINE_INSTR_SET(FPMACRO, INTMACRO) \
  FPMACRO(128, mm) \
  INTMACRO(128, mm)
#endif

#endif // INCLUDE_GREX_BACKEND_X86_OPERATIONS_HELPERS_HPP
